[tool.poetry]
name = "webapp"
version = "0.1.0"
description = ""
authors = ["Andrei Karelin <karelin74@gmail.com>"]


[tool.poetry.dependencies]
python = "^3.12"
flask = "^3.0.3"
flask-login = "^0.6.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
